version: '3.7'

networks:
  data-network:
    name: data-network

services:
  minio-server:
    restart: always
    image: minio/minio:latest
    container_name: minio
    env_file:
      - .env
    ports:
      - "9000:9000"
      - "9001:9001"
    command: "-c 'minio server /data --console-address :9001 --address :9000'"
    entrypoint: /bin/bash
    # command: "-c 'mkdir -p /data/prefect && mkdir -p /data/flow && sleep 2 && minio server /data --console-address :9001' --address ':9000'"
    environment:
      - MINIO_ROOT_USER=${AWS_ACCESS_KEY_ID}
      - MINIO_ROOT_PASSWORD=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ../volumes/minio/data:/data

    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:9000/minio/health/live"
        ]
      interval: 30s
      timeout: 20s
      retries: 3

    networks:
      - data-network
  # mc:
  #   image: minio/mc
  #   depends_on:
  #     - minio
  #   # container_name: mc
  #   env_file:
  #     - .env
  #   entrypoint: >
  #     /bin/sh -c " /tmp/wait-for-it.sh minio:9000 && /usr/bin/mc alias set minio http://minio:9000 ${AWS_ACCESS_KEY_ID} ${AWS_SECRET_ACCESS_KEY} && mkdir data/mlflow && /usr/bin/mc mb data/mlflow && /usr/bin/mc mb data/prefect; exit 0; "
  #   # volumes:
  #   #     - ./wait-for-it:/tmp/wait-for-it.sh
  #   networks:
  #     - data_stack_network